### ISSUE TITLE
Publish binary packages for windows

### ISSUE THREAD

**Issue by Clausinho** [AlexD97/MrWriter#2]
Hey, 
I would love if someone could provide binary packages for Windows for this repo, like the original repo has. I am really interested to try the pdf annotation. I currently have really slow internet, so I dont think I am able to download the required the build tools. If I somehow manage to get a faster internet access I'll build them and upload them.

Thanks

**Comment by AlexD97** [comment]
Hi,

I tried to compile it on windows, but I'm not able to link against libpoppler. Maybe you know how?

**Comment by Clausinho** [comment]
Okay so I have been trying this out for the last two hours.
I copied some source files from poppler and discount over to the MrWriter directory because I don't know how cmake or make for that matter works

~~`
/home/claus/sourcecode/mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -lmarkdown
/home/claus/sourcecode/mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -lpoppler-qt5
/home/claus/sourcecode/mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -lmarkdown
`~~
i dont know enough about make, so where should i put these libs so make recognizes them?


got poppler for windows from here:
https://github.com/markummitchell/engauge-digitizer/tree/master/dev/windows/poppler-64bit-libs/lib
now only need markdown by discount
and im using this
https://github.com/Orc/discount/

**Comment by Clausinho** [comment]
okay using the both libs above, and changing the paths in the MrWriter.pro file so that it points to the libs provided by these two repos:

I get this error

`
release/widget.o:widget.cpp:(.text$_ZN6Widget15mousePressEventEP11QMouseEvent+0x194): undefined reference to `_imp___ZNK7Poppler8LinkGoto10isExternalEv'
release/widget.o:widget.cpp:(.text$_ZN6Widget15mousePressEventEP11QMouseEvent+0x766): undefined reference to `_imp___ZNK7Poppler8LinkGoto11destinationEv'
release/widget.o:widget.cpp:(.text$_ZN6Widget15mousePressEventEP11QMouseEvent+0x77f): undefined reference to `_imp___ZNK7Poppler15LinkDestination10pageNumberEv'
release/widget.o:widget.cpp:(.text$_ZN6Widget15mousePressEventEP11QMouseEvent+0x794): undefined reference to `_imp___ZN7Poppler15LinkDestinationD1Ev'
release/widget.o:widget.cpp:(.text$_ZN6Widget15mousePressEventEP11QMouseEvent+0x1470): undefined reference to `_imp___ZN7Poppler15LinkDestinationD1Ev'
release/page.o:page.cpp:(.text$_ZNSt15_Sp_counted_ptrIPN7Poppler4PageELN9__gnu_cxx12_Lock_policyE2EE10_M_disposeEv[__ZNSt15_Sp_counted_ptrIPN7Poppler4PageELN9__gnu_cxx12_Lock_policyE2EE10_M_disposeEv]+0xf): undefined reference to `_imp___ZN7Poppler4PageD1Ev'
release/page.o:page.cpp:(.text$_ZN5MrDoc4Page6setPdfEPN7Poppler4PageEib+0x5b): undefined reference to `_imp___ZNK7Poppler4Page9pageSizeFEv'
release/page.o:page.cpp:(.text$_ZN5MrDoc4Page6setPdfEPN7Poppler4PageEib+0x173): undefined reference to `_imp___ZN7Poppler4PageD1Ev'
release/page.o:page.cpp:(.text$_ZN5MrDoc4Page15compileMarkdownERK7QString+0x72): undefined reference to `mkd_string'
release/page.o:page.cpp:(.text$_ZN5MrDoc4Page15compileMarkdownERK7QString+0x86): undefined reference to `mkd_compile'
release/page.o:page.cpp:(.text$_ZN5MrDoc4Page15compileMarkdownERK7QString+0x9a): undefined reference to `mkd_document'
release/page.o:page.cpp:(.text$_ZN5MrDoc4Page13searchPdfPrevERK7QString+0x2e): undefined reference to `_imp___ZNK7Poppler4Page6searchERK7QString6QFlagsINS0_10SearchFlagEENS0_8RotationE'
release/page.o:page.cpp:(.text$_ZN5MrDoc4Page18linkFromMouseClickEdd+0x6a): undefined reference to `_imp___ZNK7Poppler4Page5linksEv'
release/page.o:page.cpp:(.text$_ZN5MrDoc4Page18linkFromMouseClickEdd+0x131): undefined reference to `_imp___ZNK7Poppler4Link8linkAreaEv'
release/page.o:page.cpp:(.text$_ZN5MrDoc4Page5paintER8QPainterd6QRectF+0x162): undefined reference to `_imp___ZNK7Poppler4Page13renderToImageEddiiiiNS0_8RotationE'
release/document.o:document.cpp:(.text$_ZNSt15_Sp_counted_ptrIPN7Poppler8DocumentELN9__gnu_cxx12_Lock_policyE2EE10_M_disposeEv[__ZNSt15_Sp_counted_ptrIPN7Poppler8DocumentELN9__gnu_cxx12_Lock_policyE2EE10_M_disposeEv]+0xf): undefined reference to `_imp___ZN7Poppler8DocumentD1Ev'
release/document.o:document.cpp:(.text$_ZNSt12__shared_ptrIN7Poppler8DocumentELN9__gnu_cxx12_Lock_policyE2EE5resetIS1_EEvPT_[__ZNSt12__shared_ptrIN7Poppler8DocumentELN9__gnu_cxx12_Lock_policyE2EE5resetIS1_EEvPT_]+0x110): undefined reference to `_imp___ZN7Poppler8DocumentD1Ev'
release/document.o:document.cpp:(.text$_ZN5MrDoc8Document7loadPDFE7QString+0xe3): undefined reference to `_imp___ZN7Poppler8Document4loadERK7QStringRK10QByteArrayS6_'
release/document.o:document.cpp:(.text$_ZN5MrDoc8Document7loadPDFE7QString+0x16f): undefined reference to `_imp___ZNK7Poppler8Document8isLockedEv'
release/document.o:document.cpp:(.text$_ZN5MrDoc8Document7loadPDFE7QString+0x183): undefined reference to `_imp___ZN7Poppler8Document13setRenderHintENS0_10RenderHintEb'
release/document.o:document.cpp:(.text$_ZN5MrDoc8Document7loadPDFE7QString+0x1d0): undefined reference to `_imp___ZNK7Poppler8Document8numPagesEv'
release/document.o:document.cpp:(.text$_ZN5MrDoc8Document7loadPDFE7QString+0x20e): undefined reference to `_imp___ZNK7Poppler8Document4pageEi'
release/document.o:document.cpp:(.text$_ZN5MrDoc8Document7loadPDFE7QString+0x36f): undefined reference to `_imp___ZN7Poppler8DocumentD1Ev'
release/document.o:document.cpp:(.text$_ZN5MrDoc8Document7loadXOJE7QString+0xc46): undefined reference to `_imp___ZN7Poppler8Document4loadERK7QStringRK10QByteArrayS6_'
release/document.o:document.cpp:(.text$_ZN5MrDoc8Document7loadXOJE7QString+0xc7c): undefined reference to `_imp___ZN7Poppler8Document13setRenderHintENS0_10RenderHintEb'
release/document.o:document.cpp:(.text$_ZN5MrDoc8Document7loadXOJE7QString+0xd97): undefined reference to `_imp___ZNK7Poppler8Document4pageEi'
release/document.o:document.cpp:(.text$_ZN5MrDoc8Document7loadMOJE7QString+0xd7a): undefined reference to `_imp___ZN7Poppler8Document4loadERK7QStringRK10QByteArrayS6_'
release/document.o:document.cpp:(.text$_ZN5MrDoc8Document7loadMOJE7QString+0xdb0): undefined reference to `_imp___ZN7Poppler8Document13setRenderHintENS0_10RenderHintEb'
release/document.o:document.cpp:(.text$_ZN5MrDoc8Document7loadMOJE7QString+0xed1): undefined reference to `_imp___ZNK7Poppler8Document4pageEi'
`

**Comment by AlexD97** [comment]
It seems like something is wrong with the linking to poppler. Unfortunately I don't know how to solve this.

**Comment by Clausinho** [comment]
same. in the end I just switched to Xournal++
Tbh even tho it is not as smooth as some commercial alternatives, it looks fine for windows usage.
Thanks for your help. Keep rocking and contributing to OSS :)
