### ISSUE TITLE
how can  I config my wacom pen key3 to eraser?

### ISSUE THREAD

**Issue by 0DARKer** [AlexD97/MrWriter#4]

**Comment by AlexD97** [comment]
What is the current behavior when you press key3?

**Comment by 0DARKer** [comment]
select tool ,which not sequentially use

At 2019-03-21 19:19:06, "AlexD97" <notifications@github.com> wrote:


What is the current behavior when you press key3?

**Comment by AlexD97** [comment]
It seems that key3 is recognized as right mouse button. You could try to change lines 839-842 in widget.cpp to
`previousTool = currentTool; `
`emit eraser();`
`undoStack.beginMacro("erase");`
`erase(mousePos, invertEraser);`

**Comment by 0DARKer** [comment]
I solved my problem ,thanks

At 2019-03-21 23:36:39, "AlexD97" <notifications@github.com> wrote:


It seems that key3 is recognized as right button. You could try to change lines 839-842 in widget.cpp to
previousTool = currentTool;
emit eraser();
undoStack.beginMacro("erase");
erase(mousePos, invertEraser);
